# Generated by Django 5.2.16 on 2026-07-22 14:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_logindevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[apps.core.validators.validate_phone_number]),
        ),
    ]
