# Generated by Django 5.2.16 on 2026-07-23 12:03

import apps.core.upload_security
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='services_category_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('999999.99'))])),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.core.upload_security.safe_image_upload_path, validators=[apps.core.upload_security.validate_image_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ('category__name', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 480)), name='services_service_duration_valid'), models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0.00'))), name='services_service_price_positive'), models.UniqueConstraint(models.F('category'), django.db.models.functions.text.Lower('name'), name='services_service_category_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=160)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_ACCEPTING', 'Not accepting appointments'), ('ON_LEAVE', 'On leave')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__email'),
                'constraints': [models.CheckConstraint(condition=models.Q(('availability_status__in', ('AVAILABLE', 'NOT_ACCEPTING', 'ON_LEAVE'))), name='services_staff_availability_valid')],
            },
        ),
    ]
