# Generated by Django 5.2.17 on 2026-10-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_saleitem_product'),
        ('services', '0002_staffprofile_skills_product_staffschedule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
