# Generated by Django 5.2.17 on 2026-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='lunch_end',
            field=models.TimeField(blank=True, default='13:00:00', null=True),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='lunch_start',
            field=models.TimeField(blank=True, default='12:00:00', null=True),
        ),
    ]
