# Generated by Django 5.2.16 on 2026-07-23 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('TRAINED', 'Trained'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('FAILED', 'Failed')], max_length=20)),
                ('model_type', models.CharField(default='RandomForestRegressor', max_length=100)),
                ('training_start', models.DateField()),
                ('training_end', models.DateField()),
                ('parameters', models.JSONField(default=dict)),
                ('feature_columns', models.JSONField(default=list)),
                ('service_categories', models.JSONField(default=list)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('training_count', models.PositiveIntegerField(default=0)),
                ('test_count', models.PositiveIntegerField(default=0)),
                ('distinct_days', models.PositiveIntegerField(default=0)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('sklearn_version', models.CharField(blank=True, max_length=30)),
                ('pandas_version', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('service_category', models.CharField(max_length=100)),
                ('predicted_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasting.forecastrun')),
            ],
            options={
                'ordering': ('forecast_date', 'service_category'),
            },
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.CheckConstraint(condition=models.Q(('training_end__gte', models.F('training_start'))), name='forecast_training_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('TRAINED', 'INSUFFICIENT_DATA', 'FAILED'))), name='forecast_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.UniqueConstraint(fields=('run', 'forecast_date', 'service_category'), name='forecast_result_run_date_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.CheckConstraint(condition=models.Q(('predicted_sales__gte', 0)), name='forecast_predicted_sales_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.CheckConstraint(condition=models.Q(('lower_bound__gte', 0)), name='forecast_lower_bound_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.CheckConstraint(condition=models.Q(('upper_bound__gte', models.F('lower_bound'))), name='forecast_bounds_valid'),
        ),
    ]
