# Generated by Django 5.2.16 on 2026-07-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_appointmentservice_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], max_length=12)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.appointmentservice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('old_status', models.F('new_status')), _negated=True), name='service_status_transition_changes_state')],
            },
        ),
    ]
