# Generated by Django 5.2.16 on 2026-07-22 13:34

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.bookings.models.generate_booking_reference, editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('service_name', models.CharField(max_length=160)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='UNVERIFIED', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('verification_code_digest', models.CharField(blank=True, max_length=64)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_resend_count', models.PositiveSmallIntegerField(default=0)),
                ('public_access_token_digest', models.CharField(blank=True, max_length=64)),
                ('public_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
