# Generated by Django 5.2.16 on 2026-07-23 12:35

import apps.bookings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_phone_number'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default=apps.bookings.models.generate_booking_reference, editable=False, max_length=32, unique=True)),
                ('customer_name_snapshot', models.CharField(max_length=201)),
                ('customer_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('booking_source', models.CharField(choices=[('PUBLIC', 'Public booking'), ('WALK_IN', 'Walk-in'), ('STAFF', 'Staff-created')], default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('RESCHEDULED', 'Rescheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No-show'), ('EXPIRED', 'Verification expired')], default='UNVERIFIED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('verification_code_digest', models.CharField(blank=True, max_length=64)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verification_resend_count', models.PositiveSmallIntegerField(default=0)),
                ('public_access_token_digest', models.CharField(blank=True, max_length=64)),
                ('public_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('requires_schedule_review', models.BooleanField(default=False)),
                ('legacy_booking_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer')),
            ],
            options={
                'ordering': ('appointment_date', 'start_time', 'booking_reference'),
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=160)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='bookings.appointment')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_service_rows', to='services.service')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_services',
            field=models.ManyToManyField(related_name='appointments', through='bookings.AppointmentService', to='services.service'),
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('RESCHEDULED', 'Rescheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No-show'), ('EXPIRED', 'Verification expired')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.appointment')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.UniqueConstraint(fields=('appointment', 'position'), name='appointment_service_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 480)), name='appointment_service_duration_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='appointment_service_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_staff', 'appointment_date', 'status'], name='appointment_staff_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('UNVERIFIED', 'PENDING', 'APPROVED', 'RESCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'REJECTED', 'NO_SHOW', 'EXPIRED'))), name='appointment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('booking_source__in', ('PUBLIC', 'WALK_IN', 'STAFF'))), name='appointment_source_valid'),
        ),
    ]
