# Generated by Django 5.2.16 on 2026-07-22 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCEEDED', 'Successful login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('ACCOUNT_LOCKED', 'Account lockout'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('EMAIL_VERIFIED', 'Email verified'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_CHANGED', 'Password changed'), ('MFA_ENABLED', 'MFA enabled'), ('MFA_DISABLED', 'MFA disabled'), ('MFA_RECOVERY_USED', 'MFA recovery used'), ('MFA_RECOVERY_RESET', 'MFA recovery reset'), ('ROLE_CHANGED', 'Role changed'), ('SESSION_REVOKED', 'Session revocation'), ('UNAUTHORIZED_ACCESS', 'Unauthorized access attempt'), ('SENSITIVE_REAUTHENTICATION', 'Sensitive-action reauthentication'), ('BOOKING_VERIFIED', 'Booking verified')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
