# Generated by Django 5.2.16 on 2026-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0002_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCEEDED', 'Successful login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('ACCOUNT_LOCKED', 'Account lockout'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('EMAIL_VERIFIED', 'Email verified'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_CHANGED', 'Password changed'), ('MFA_ENABLED', 'MFA enabled'), ('MFA_DISABLED', 'MFA disabled'), ('MFA_FAILED', 'MFA code rejected'), ('MFA_LOCKED', 'MFA temporarily locked'), ('MFA_RECOVERY_USED', 'MFA recovery used'), ('MFA_RECOVERY_RESET', 'MFA recovery reset'), ('ROLE_CHANGED', 'Role changed'), ('SESSION_REVOKED', 'Session revocation'), ('UNAUTHORIZED_ACCESS', 'Unauthorized access attempt'), ('SENSITIVE_REAUTHENTICATION', 'Sensitive-action reauthentication'), ('BOOKING_VERIFIED', 'Booking verified')], db_index=True, max_length=50),
        ),
    ]
