# Generated by Django 5.2.16 on 2026-07-23 13:40

from django.db import migrations, models


def populate_service_categories(apps, schema_editor):
    SaleItem = apps.get_model("pos", "SaleItem")
    for item in SaleItem.objects.select_related("service__category").iterator():
        if item.service_id and item.service.category_id:
            item.service_category = item.service.category.name
            item.save(update_fields=("service_category",))


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_seed_receipt_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='service_category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.RunPython(populate_service_categories, migrations.RunPython.noop),
    ]
