# Generated by Django 5.2.17 on 2026-10-05 12:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_initialize_service_monitoring'),
        ('customers', '0002_customer_user'),
        ('pos', '0003_saleitem_service_category'),
        ('services', '0002_staffprofile_skills_product_staffschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting cash drawer amount / till float.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Actual physical cash counted at shift end.', max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Expected drawer total: opening_cash + cash_sales.', max_digits=12, null=True)),
                ('cash_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Discrepancy (over/short): closing_cash - expected_cash.', max_digits=12, null=True)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ewallet_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bank_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='PromoVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount in PHP (capping rule).', max_digits=12, null=True)),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total times this voucher may be claimed.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='sale',
            name='sale_discount_type_valid',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_id_name',
            field=models.CharField(blank=True, help_text='Name printed on Senior Citizen or PWD ID.', max_length=160),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_id_number',
            field=models.CharField(blank=True, help_text='Senior Citizen or PWD identification card number.', max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='services.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No discount'), ('FIXED', 'Fixed amount'), ('PERCENT', 'Percentage'), ('SENIOR_CITIZEN', 'Senior Citizen (20%)'), ('PWD', 'PWD (20%)'), ('PROMO_VOUCHER', 'Promo voucher')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.cashiershift'),
        ),
        migrations.AddField(
            model_name='sale',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.promovoucher'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ('NONE', 'FIXED', 'PERCENT', 'SENIOR_CITIZEN', 'PWD', 'PROMO_VOUCHER'))), name='sale_discount_type_valid'),
        ),
    ]
