# Generated by Django 5.2.17 on 2026-10-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_cashiershift_promovoucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
    ]
