# Generated by Django 5.2.16 on 2026-07-23 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_appointment_appointmentservice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEW', 'New appointment'), ('APPROVED', 'Appointment approved'), ('REJECTED', 'Appointment rejected'), ('RESCHEDULED', 'Appointment rescheduled'), ('CANCELLED', 'Appointment cancelled')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notification_unread_idx')],
            },
        ),
    ]
